# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 21:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itemsapp', '0004_auto_20170317_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tags',
            new_name='tag',
        ),
    ]
